variables:
  archive_scheme: Linhome 
  archive_path: linhome.xcarchive
  export_path: linhome-adhoc-ipa
  export_options_plist: linhome-adhoc.plist
  GIT_SUBMODULE_STRATEGY: recursive

.linux-prepare:

 before_script:
   ##
   ## If a LINDOOR_USER_KEY is defined then start ssh-agent and add the key
   ##
   - if ! [ -z ${LINDOOR_USER_KEY+x} ]; then echo "$LINDOOR_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi
   - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then echo "$SCP_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi

job-ios:

  extends: .linux-prepare

  stage: build
  tags: [ "macosx-xcode11" ]

  script:
    - pod install --repo-update --verbose
    - pwd
    - xcodebuild archive -scheme $archive_scheme -archivePath ./$archive_path -configuration Release -workspace ./linhome.xcworkspace -UseModernBuildSystem=YES  -allowProvisioningUpdates
    - xcodebuild -exportArchive -archivePath  ./$archive_path -exportPath ./$export_path -exportOptionsPlist ./$export_options_plist -allowProvisioningUpdates -UseModernBuildSystem=YES
    - mv $export_path/$archive_scheme.ipa $export_path/$archive_scheme-`./git-version.sh`.ipa


  artifacts:
    paths:
      - $archive_path
      - $export_path
    when: always
    expire_in: 1 week

